### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by afc163** [afc163/afc163.github.io#2]
- [x] MockJS Random 改进
- [x] angular-resource 自定义 header 方式
- [x] spmjs.io 的样式和模板文档
- [x] Arale 和 Alice 文档迁移
- [x] web components 学习
